### ISSUE TITLE
Wrong description of what can be passed to a guard

### ISSUE THREAD

**Issue by akrzemi1** [Lastique/scope#12]
https://github.com/Lastique/scope/blob/2cd37e97c91fb1e76bdb8d33464cf89ea42923be/doc/scope_guards.qbk#L17 says:

> The wrapped action function object is specified on the scope guard construction and cannot be changed afterwards. It must be one of:
> 
> * a user-defined class with a public `operator()` taking no arguments, or
> * an lvalue reference to such class, or
> * an lvalue reference or pointer to a function taking no arguments.

There is something wrong with this description. Are you describing *types* that are allowed or *objects* that are allowed?

**Comment by Lastique** [comment]
The requirements are placed on the type of the action function object. I.e. "It must be one of *the following types*:"

**Comment by akrzemi1** [comment]
Then maybe change "It must be one of:" to "Its type must be one of:".

**Comment by Lastique** [comment]
Fixed, thanks.
